# Generated by Django 5.1.2 on 2024-10-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productidentifier_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidentifier',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_identifier', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='unitMeansureId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitmensuare'),
        ),
        migrations.AlterField(
            model_name='productoptionvariant',
            name='productVariantId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_variant', to='inventory.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='inventory.product'),
        ),
    ]
