# Generated by Django 5.1.2 on 2024-10-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productidentifier_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidentifier',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_identifier', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productoptionvariant',
            name='productVariantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_variants', to='inventory.productvariant'),
        ),
    ]
