# Generated by Django 5.1.2 on 2024-10-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productidentifier_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionvariant',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='inventory.product'),
        ),
    ]
