# Generated by Django 5.1.2 on 2024-10-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_productoptionvariant_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidentifier',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_identifier', to='inventory.product'),
        ),
    ]
