# Generated by Django 5.1.2 on 2024-10-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_productprice_cost_alter_productprice_istax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='minStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='sellOutStock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
