# Generated by Django 5.1.2 on 2024-11-22 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_productinventory_minstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productidentifier',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='unitMeansureId',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='revenue',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productoptionvariant',
            name='state',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='state',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductCombination',
            fields=[
                ('productCombinationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_combinations', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='productprice',
            name='productCombination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combination_prices', to='inventory.productcombination'),
        ),
        migrations.CreateModel(
            name='ProductOptionCombination',
            fields=[
                ('productOptionCombinationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('productCombinationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_combinations', to='inventory.productcombination')),
            ],
        ),
        migrations.AddField(
            model_name='productprice',
            name='productOptionCombination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_combination_prices', to='inventory.productoptioncombination'),
        ),
        migrations.DeleteModel(
            name='OrganizationProduct',
        ),
        migrations.DeleteModel(
            name='ProductIdentifier',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
