# Generated by Django 5.1.2 on 2024-11-28 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_product_subcategoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('combinationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('typeCollection', models.CharField(choices=[(0, 'MANUAL'), (1, 'INTELIGENTE')], default=0, max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CombinationDetails',
            fields=[
                ('combinationDetailsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('combinationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combination_details', to='inventory.collection')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combination_details', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='IntelligentCombination',
            fields=[
                ('intelligentCombinationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conditionName', models.CharField(choices=[('title', 'Titulo'), ('type', 'Tipo'), ('category', 'Categoria'), ('vendor', 'Proveedor'), ('tag', 'Etiqueta'), ('price', 'Precio'), ('comparePrice', 'Precio de comparación'), ('weight', 'Peso'), ('stock', 'Existencia de inventario'), ('variantTitle', 'Titulo de la variante')], default='title', max_length=100)),
                ('conditionValue', models.CharField(choices=[('equals', 'es igual a'), ('not_equals', 'no es igual a'), ('starts_with', 'comienza con'), ('ends_with', 'termina en'), ('contains', 'contiene'), ('not_contains', 'no contiene'), ('greater_than', 'es mayor que'), ('less_than', 'es menor que')], default='equals', max_length=100)),
                ('combinationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligent_combinations', to='inventory.collection')),
            ],
        ),
    ]
